version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5439:5432" #Esto significa que saldrá en el puerto 5439 todo lo que exponga el puerto 5432 del contenedor
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data